export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmApiUrl: process.env.OPENAI_BASE_URL ?? process.env.BUILT_IN_FORGE_API_URL ?? "",
  llmApiKey: process.env.OPENAI_API_KEY ?? process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmModel: process.env.OPENAI_MODEL ?? process.env.BUILT_IN_FORGE_MODEL ?? "gemini-2.5-flash",
  difyApiUrl: process.env.DIFY_API_URL ?? "",
  difyApiKey: process.env.DIFY_API_KEY ?? "",
  difyUser: process.env.DIFY_USER ?? "category-weekly-report",
  localAuthBypass: process.env.LOCAL_AUTH_BYPASS === "true",
  feishuAppId: process.env.FEISHU_APP_ID ?? "",
  feishuAppSecret: process.env.FEISHU_APP_SECRET ?? "",
  feishuRedirectBaseUrl: process.env.FEISHU_REDIRECT_BASE_URL ?? "",
};
